"""ai_research/05_mcp_integration: enumerate the MCP gateway's static tool schema.

The MCP gateway exposes Honba's read-only capabilities as Model Context Protocol
tools. The schema is generated by the Rust codegen (`honba-codegen`) into
``schema/mcp/mcp_tools.json`` at build time — no server needs to run and no
real LLM is required to discover what tools exist. This example loads that
schema and reports the six tools with their names, descriptions, input/output
schemas, and the ``readOnlyHint`` annotation.

This is the offline, scaffold-only variant. The live gateway (`honba mcp serve`,
P1 in the roadmap) would host these same six tools over stdio/HTTP, backed by
the Rust HTTP API (`honba-api-rest`).

Run::

    python ai_research/05_mcp_integration.py
    python ai_research/05_mcp_integration.py --out mcp_tools.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    import honba_examples  # noqa: F401
except ModuleNotFoundError:  # plain checkout without `pip install -e .`
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from honba_examples.jsonable import jsonable


def _schema_path() -> Path:
    """Locate the committed MCP schema: honba/schema/mcp/mcp_tools.json relative
    to the honba checkout next to this repo, or the repo's own copy if present.
    """
    # This repo: honba-labs/honba-examples/
    # Sibling honba checkout: honba-labs/honba/
    repo_root = Path(__file__).resolve().parents[1]
    candidates = [
        repo_root.parent / "honba" / "schema" / "mcp" / "mcp_tools.json",
        repo_root / "honba" / "schema" / "mcp" / "mcp_tools.json",
    ]
    for c in candidates:
        if c.exists():
            return c
    # Fallback: the example repo itself might carry a copy for docs purposes
    for c in [repo_root / "honba" / "schema" / "mcp" / "mcp_tools.json"]:
        if c.exists():
            return c
    raise FileNotFoundError(
        "MCP schema not found. Expected at ../honba/schema/mcp/mcp_tools.json "
        "relative to this repo, or run `make mcp` in the honba checkout."
    )


def run() -> dict[str, Any]:
    """Load the MCP tool schema and return a JSON-serializable summary."""
    path = _schema_path()
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    tools = data.get("tools", [])
    summary = {
        "schema_path": str(path),
        "comment": data.get("$comment"),
        "tool_count": len(tools),
        "tools": [
            {
                "name": t.get("name"),
                "description": t.get("description"),
                "read_only": t.get("annotations", {}).get("readOnlyHint"),
                "input_schema": jsonable(t.get("inputSchema")),
                "output_schema": jsonable(t.get("outputSchema")),
            }
            for t in tools
        ],
    }
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument("--out", type=Path, default=None, help="also write the JSON here")
    args = parser.parse_args(argv)

    result = run()

    text = json.dumps(result, indent=2, default=str)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())